In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
np.mean([ 0, 2, 4, 5, 5, 6, 8, 10])

5.0

In [4]:
x = [-1, 0, 1]
y = [-5, 0, 5]

print(np.mean(x))
print(np.var(x))

print(np.mean(y))
print(np.var(y))

0.0
0.6666666666666666
0.0
16.666666666666668


In [5]:
np.var??

In [22]:
x = np.array([65, 50, 55, 65, 55, 70, 65, 70])
y = np.array([85, 74, 76, 90, 85, 87, 94, 98])

n_xy = np.sum(x*y)
n_xy

42990

In [15]:
n = 8

In [9]:
sum_x = np.sum(x)
sum_y = np.sum(y)

In [10]:
sum_x_2 = np.sum(x**2)
sum_x_whole_2 = np.sum(x) ** 2

In [12]:
sum_x_whole_2

245025

In [16]:
m = ((n*n_xy) - (sum_x*sum_y))/((n*sum_x_2) - sum_x_whole_2)
m

0.9023622047244094

In [17]:
np.var([ 0, 2, 4, 5, 5, 6, 8, 10])

8.75

In [18]:
b = (np.sum(y)/n) - (m*(np.sum(x)/n))
b

30.29133858267717

In [19]:
np.sum(x)

495

In [33]:
x = np.array([2, 4, 6])
y = np.array([5, 10, 15])

np.cov((x, y))

array([[ 4., 10.],
       [10., 25.]])

In [34]:
np.sum(x*y)

140

In [35]:
(np.sum(x*y)) - (np.sum(x) * np.sum(y))

-220

In [36]:
np.sum( (x - np.sum(x))*(y - np.sum(y)) )

500

In [37]:
np.mean( (x - np.mean(x))*(y - np.mean(y)) )

6.666666666666667

In [41]:
a = np.array([[1,0,0],[0,1,0],[0,0,1]])
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [43]:
a.transpose()

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [46]:
np.linalg.inv(a)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])